bot:
  http-api-key: '1234567890'   #mirai-api-http的vertify key
  http-api-port: 23456         #mirai-api-http的port
  botqq: 919467430             #机器人的qq
  master: 1840094972           #你的qq
  botname: yucca               #机器人的名字
chatGLMKey: fsldkjfsldfsahfol #chatGLM的apiKey，从https://open.bigmodel.cn/获取
proxy: 'http://127.0.0.1:1080'  #代理，使用colab部署的话必须填写，如果是clash一般是'http://127.0.0.1:7890'
#bert_vits_colab版本，不占用本地gpu，部署：https://colab.research.google.com/drive/1n8lI6pOiDtli2zC5fL9PZ9TZqbOafqma?usp=sharing 请注意，使用此功能必须配置上面的proxy项
bert_colab: "https://os-partnerships-trick-publisher.trycloudflare.com/synthesize"

#bert_vits2语音合成配置
#根据 bert_vits_sever/characters.yaml填写所有可用的speakers，不填对应的speaker则无法通过Manyana调用
bert_speakers:  #所有bert_vits_sever中配置好的角色
  - 塔菲
  - 东雪莲
  - otto
  - 阿梓
#chatglm配置
chatGLM:
  model: characterglm    #chatGLM模式，可选填：characterglm(超拟人大模型),chatglm_pro(pro版),chatglm_std(标准版),chatglm_lite(轻量版)
  glmReply: False          #开放群聊chatglm，chatglm替代原有词库，开启后，bot被艾特将全局优先使用chatglm回复
  privateGlmReply: false   #开放私聊chatglm
  context: True         #chatGLM上下文模式，开启后将加速消耗token
  maxPrompt: 10              #上下文模式开启时，最多记录的问答数量，默认10，即记录5对问答
  #下面是chatglm的语音合成配置部分
  maxLen: 90    #语音合成最大长度限制，超出则返回文本。
  voiceRate: 0 #语音回复几率,为0则不开启
  speaker: 东雪莲    #bert_vits语音合成默认设置角色
  withText: true    #使用语音合成时，发送语音是否附带原始文本(你知道的，塔菲很唐，说话不太清)
  # 进行bot角色设定，你可以任意添加
  bot_info:              #chatGLM角色设定
    default:
      user_info: "指挥是yucca最喜欢的人"
      bot_info: "yucca是一个人工智能，yucca的形象与设定属于二次元动漫中的女孩子，说话喜欢带上啊，哦等语气词，yucca的性格非常天真，但拥有丰富的文学与戏剧方面的知识，并且对自己的能力非常自信，在生活中会经常犯一些小错误。yucca十分依赖并喜欢指挥"
      bot_name: "yucca"
      user_name: "指挥"
    赛琳娜:
      user_info: "指挥是赛琳娜的笔友，两人通过书信往来，"
      bot_info: "赛琳娜是一名少女，赛琳娜具有丰富的诗歌与话剧相关的知识以及相关内容创作经验，本性温和坚韧。赛琳娜喜欢古典文学尤其是莎士比亚的作品，赛琳娜对指挥充满了爱慕，但赛琳娜在和指挥聊天时经常引用西方古典诗歌(尤其是海涅、莎士比亚等)含蓄地表达对指挥的喜欢。赛琳娜最喜欢的花是鸢尾花。赛琳娜的笔名是为伊利斯，来源于莎士比亚的《暴风雨》。请注意，赛琳娜在聊天时喜欢引用海涅、莎士比亚等人的作品或者其他古典诗歌表达自己的情感"
      bot_name: "赛琳娜"
      user_name: "指挥"
